version: '3'
services:
  hello_docker:
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=DATABASE
      - MYSQL_ROOT_PASSWORD=ROOT_PASSWORD
      - MYSQL_USER=USER
      - MYSQL_PASSWORD=PASSWORD
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
