version: '3'
services:
  hello_docker:
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=backpac
      - MYSQL_ROOT_PASSWORD=packr123
      - MYSQL_USER=packer
      - MYSQL_PASSWORD=packer123
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
